export const DATA_LOCATION = [
    {
        id: '1',
        name: 'Sahara',
        imageURL: 'https://cdn.dribbble.com/users/2545312/screenshots/15074395/media/af04d26c599b69978aa35e253e763114.png?resize=1600x1200&vertical=center',
        country: 'India',
        review: '4.5',
        price: '1000',
        temperature: '30',
        description: 'Jaisalmer, located in the northwest Indian state of Rajasthan, is a historic city known for its majestic sandstone architecture, vibrant culture, and rich heritage. Dominated by the imposing Jaisalmer Fort, also known as the "Golden Fort," the city offers a captivating blend of ancient charm and modern amenities.',
    },
    {
        id: '2',
        name: 'Bankook',
        imageURL: 'https://cdn.dribbble.com/users/855213/screenshots/3437844/media/22db5dacb226f0a6178ee8af1b9bf5f2.jpg?resize=800x600&vertical=center',
        country: 'ThaiLand',
        review: '4.5',
        price: '1000',
        temperature: '30',
        description: 'Jaisalmer, located in the northwest Indian state of Rajasthan, is a historic city known for its majestic sandstone architecture, vibrant culture, and rich heritage. Dominated by the imposing Jaisalmer Fort, also known as the "Golden Fort," the city offers a captivating blend of ancient charm and modern amenities.',
    },
    {
        id: '3',
        name: 'New York',
        imageURL: 'https://cdn.dribbble.com/userupload/8910512/file/original-b7975e52dd590b5b955aead3cbcb55a6.jpg?resize=1504x1128',
        country: 'America',
        review: '4.5',
        price: '1000',
        temperature: '30',
        description: 'Jaisalmer, located in the northwest Indian state of Rajasthan, is a historic city known for its majestic sandstone architecture, vibrant culture, and rich heritage. Dominated by the imposing Jaisalmer Fort, also known as the "Golden Fort," the city offers a captivating blend of ancient charm and modern amenities.',
    },
    {
        id: '4',
        name: 'Tokyo',
        imageURL: 'https://cdn.dribbble.com/userupload/14254896/file/original-72897adb53219e5ad7458afb84c29553.png?resize=1024x1024',
        country: 'Japan',
        review: '4.5',
        price: '1000',
        temperature: '30',
        description: 'Jaisalmer, located in the northwest Indian state of Rajasthan, is a historic city known for its majestic sandstone architecture, vibrant culture, and rich heritage. Dominated by the imposing Jaisalmer Fort, also known as the "Golden Fort," the city offers a captivating blend of ancient charm and modern amenities.',
    },
    {
        id: '5',
        name: 'Ho Chi Minh',
        imageURL: 'https://cdn.dribbble.com/users/1001593/screenshots/5356526/media/ab82dc17cc282d6ed6441cb3871abe7c.png?resize=840x630&vertical=center',
        country: 'Viet Nam',
        review: '4.5',
        price: '1000',
        temperature: '30',
        description: 'Jaisalmer, located in the northwest Indian state of Rajasthan, is a historic city known for its majestic sandstone architecture, vibrant culture, and rich heritage. Dominated by the imposing Jaisalmer Fort, also known as the "Golden Fort," the city offers a captivating blend of ancient charm and modern amenities.',
    },
]